---
title: "MIS011-Table2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
source(here::here("0-config.R"))
source(here("audrie R scripts/observational/quartileTMLE_telo_growth.R"))
```

```{r}
tbl <- data.table("Outcome"=character(), "N"=numeric(), "Q1 Mean"=numeric(), "Q2 Mean"=numeric(), "Q3 Mean"=numeric(), "Q4 Mean"=numeric(), "Unadjusted"=character(), "Fully adjusted"=character(), "Unadjusted"=character(), "Fully adjusted"=character(), "Unadjusted"=character(), "Fully adjusted"=character())
```

```{r}
round_df <- function(df, digits) {
  nums <- vapply(df, is.numeric, FUN.VALUE = logical(1))

  df[,nums] <- round(df[,nums], digits = digits)

  (df)
}

#Hypothesis 4
h4adj.res <- round_df(h4adj.res, 2)
h4unadj.res <- round_df(h4unadj.res, 2)

#LAZ Year 1
Nlazy1 <- nrow(h4_laz_t2_vs_ts_t2gam.res)
lazy1unadj <- filter(h4unadj.res, Y == "laz_t2")
lazy1adj <- filter(h4adj.res, Y == "laz_t2")
tbl <- rbind(tbl, list("Outcome" = "LAZ, Year 1", "N" = Nlazy1, "Q1 Mean" = lazy1unadj$meanY[1], "Q2 Mean" =lazy1unadj$meanY[2], "Q3 Mean" = lazy1unadj$meanY[3], "Q4 Mean" = lazy1unadj$meanY[4],
                       "Unadjusted" = paste(lazy1unadj$ATE[2], ", (", lazy1unadj$CI1[2], ", ", lazy1unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(lazy1adj$ATE[2], ", (", lazy1adj$CI1[2], ", ", lazy1adj$CI2[2], ")"),
                       "Unadjusted" = paste(lazy1unadj$ATE[3], ", (", lazy1unadj$CI1[3], ", ", lazy1unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(lazy1adj$ATE[3], ", (", lazy1adj$CI1[3], ", ", lazy1adj$CI2[3], ")"),
                       "Unadjusted" = paste(lazy1unadj$ATE[4], ", (", lazy1unadj$CI1[4], ", ", lazy1unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(lazy1adj$ATE[4], ", (", lazy1adj$CI1[4], ", ", lazy1adj$CI2[4], ")")), stringsAsFactors=FALSE)

#WAZ Year 1
Nwazy1 <- nrow(h4_waz_t2_vs_ts_t2gam.res)
wazy1unadj <- filter(h4unadj.res, Y == "waz_t2")
wazy1adj <- filter(h4adj.res, Y == "waz_t2")
tbl <- rbind(tbl, list("Outcome"="WAZ, Year 1", "N"=Nwazy1, "Q1 Mean"=wazy1unadj$meanY[1], "Q2 Mean"=wazy1unadj$meanY[2], "Q3 Mean"=wazy1unadj$meanY[3], "Q4 Mean" = wazy1unadj$meanY[4],
                       "Unadjusted" = paste(wazy1unadj$ATE[2], ", (", wazy1unadj$CI1[2], ", ", wazy1unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wazy1adj$ATE[2], ", (", wazy1adj$CI1[2], ", ", wazy1adj$CI2[2], ")"),
                       "Unadjusted" = paste(wazy1unadj$ATE[3], ", (", wazy1unadj$CI1[3], ", ", wazy1unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wazy1adj$ATE[3], ", (", wazy1adj$CI1[3], ", ", wazy1adj$CI2[3], ")"),
                       "Unadjusted" = paste(wazy1unadj$ATE[4], ", (", wazy1unadj$CI1[4], ", ", wazy1unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wazy1adj$ATE[4], ", (", wazy1adj$CI1[4], ", ", wazy1adj$CI2[4], ")")), stringsAsFactors=FALSE)

#WLZ Year 1
Nwlzy1 <- nrow(h4_whz_t2_vs_ts_t2gam.res)
wlzy1unadj <- filter(h4unadj.res, Y == "whz_t2")
wlzy1adj <- filter(h4adj.res, Y == "whz_t2")
tbl <- rbind(tbl, list("Outcome"="WLZ, Year 1", "N"=Nwlzy1, "Q1 Mean"=wlzy1unadj$meanY[1], "Q2 Mean"=wlzy1unadj$meanY[2], "Q3 Mean"=wlzy1unadj$meanY[3], "Q4 Mean" = wlzy1unadj$meanY[4],
                       "Unadjusted" = paste(wlzy1unadj$ATE[2], ", (", wlzy1unadj$CI1[2], ", ", wlzy1unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wlzy1adj$ATE[2], ", (", wlzy1adj$CI1[2], ", ", wlzy1adj$CI2[2], ")"),
                       "Unadjusted" = paste(wlzy1unadj$ATE[3], ", (", wlzy1unadj$CI1[3], ", ", wlzy1unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wlzy1adj$ATE[3], ", (", wlzy1adj$CI1[3], ", ", wlzy1adj$CI2[3], ")"),
                       "Unadjusted" = paste(wlzy1unadj$ATE[4], ", (", wlzy1unadj$CI1[4], ", ", wlzy1unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wlzy1adj$ATE[4], ", (", wlzy1adj$CI1[4], ", ", wlzy1adj$CI2[4], ")")), stringsAsFactors=FALSE)

#HCZ Year 1
Nhczy1 <- nrow(h4_hcz_t2_vs_ts_t2gam.res)
hczy1unadj <- filter(h4unadj.res, Y == "hcz_t2")
hczy1adj <- filter(h4adj.res, Y == "hcz_t2")
tbl <- rbind(tbl, list("Outcome"="HCZ, Year 1", "N"=Nhczy1, "Q1 Mean"=hczy1unadj$meanY[1], "Q2 Mean"=hczy1unadj$meanY[2], "Q3 Mean"=hczy1unadj$meanY[3], "Q4 Mean" = hczy1unadj$meanY[4],
                       "Unadjusted" = paste(hczy1unadj$ATE[2], ", (", hczy1unadj$CI1[2], ", ", hczy1unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(hczy1adj$ATE[2], ", (", hczy1adj$CI1[2], ", ", hczy1adj$CI2[2], ")"),
                       "Unadjusted" = paste(hczy1unadj$ATE[3], ", (", hczy1unadj$CI1[3], ", ", hczy1unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(hczy1adj$ATE[3], ", (", hczy1adj$CI1[3], ", ", hczy1adj$CI2[3], ")"),
                       "Unadjusted" = paste(hczy1unadj$ATE[4], ", (", hczy1unadj$CI1[4], ", ", hczy1unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(hczy1adj$ATE[4], ", (", hczy1adj$CI1[4], ", ", hczy1adj$CI2[4], ")")), stringsAsFactors=FALSE)

#blank row
tbl <- rbind(tbl, list("Outcome"=" ", "N"=" ", "Q1 Mean"=" ", "Q2 Mean"=" ", "Q3 Mean"=" ", "Q4 Mean"=" ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" =" "), stringsAsFactors=FALSE)
```

```{r}
#Hypothesis 6
h6adj.res <- round_df(h6adj.res, 2)
h6unadj.res <- round_df(h6unadj.res, 2)

#LAZ Year 2
Nlazy2 <- nrow(h6_laz_t3_vs_ts_t2gam.res)
lazy2unadj <- filter(h6unadj.res, Y == "laz_t3")
lazy2adj <- filter(h6adj.res, Y == "laz_t3")
tbl <- rbind(tbl, list("Outcome" = "LAZ, Year 2", "N" = Nlazy2, "Q1 Mean" = lazy2unadj$meanY[1], "Q2 Mean" =lazy2unadj$meanY[2], "Q3 Mean" = lazy2unadj$meanY[3], "Q4 Mean" = lazy2unadj$meanY[4],
                       "Unadjusted" = paste(lazy2unadj$ATE[2], ", (", lazy2unadj$CI1[2], ", ", lazy2unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(lazy2adj$ATE[2], ", (", lazy2adj$CI1[2], ", ", lazy2adj$CI2[2], ")"),
                       "Unadjusted" = paste(lazy2unadj$ATE[3], ", (", lazy2unadj$CI1[3], ", ", lazy2unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(lazy2adj$ATE[3], ", (", lazy2adj$CI1[3], ", ", lazy2adj$CI2[3], ")"),
                       "Unadjusted" = paste(lazy2unadj$ATE[4], ", (", lazy2unadj$CI1[4], ", ", lazy2unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(lazy2adj$ATE[4], ", (", lazy2adj$CI1[4], ", ", lazy2adj$CI2[4], ")")), stringsAsFactors=FALSE)

#WAZ Year 2
Nwazy2 <- nrow(h6_waz_t3_vs_ts_t2gam.res)
wazy2unadj <- filter(h6unadj.res, Y == "waz_t3")
wazy2adj <- filter(h6adj.res, Y == "waz_t3")
tbl <- rbind(tbl, list("Outcome" = "WAZ, Year 2", "N" = Nwazy2, "Q1 Mean" = wazy2unadj$meanY[1], "Q2 Mean" =wazy2unadj$meanY[2], "Q3 Mean" = wazy2unadj$meanY[3], "Q4 Mean" = wazy2unadj$meanY[4],
                       "Unadjusted" = paste(wazy2unadj$ATE[2], ", (", wazy2unadj$CI1[2], ", ", wazy2unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wazy2adj$ATE[2], ", (", wazy2adj$CI1[2], ", ", wazy2adj$CI2[2], ")"),
                       "Unadjusted" = paste(wazy2unadj$ATE[3], ", (", wazy2unadj$CI1[3], ", ", wazy2unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wazy2adj$ATE[3], ", (", wazy2adj$CI1[3], ", ", wazy2adj$CI2[3], ")"),
                       "Unadjusted" = paste(wazy2unadj$ATE[4], ", (", wazy2unadj$CI1[4], ", ", wazy2unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wazy2adj$ATE[4], ", (", wazy2adj$CI1[4], ", ", wazy2adj$CI2[4], ")")), stringsAsFactors=FALSE)

#WLZ Year 2
Nwlzy2 <- nrow(h6_whz_t3_vs_ts_t2gam.res)
wlzy2unadj <- filter(h6unadj.res, Y == "whz_t3")
wlzy2adj <- filter(h6adj.res, Y == "whz_t3")
tbl <- rbind(tbl, list("Outcome" = "WLZ, Year 2", "N" = Nwlzy2, "Q1 Mean" = wlzy2unadj$meanY[1], "Q2 Mean" =wlzy2unadj$meanY[2], "Q3 Mean" = wlzy2unadj$meanY[3], "Q4 Mean" = wlzy2unadj$meanY[4],
                       "Unadjusted" = paste(wlzy2unadj$ATE[2], ", (", wlzy2unadj$CI1[2], ", ", wlzy2unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wlzy2adj$ATE[2], ", (", wlzy2adj$CI1[2], ", ", wlzy2adj$CI2[2], ")"),
                       "Unadjusted" = paste(wlzy2unadj$ATE[3], ", (", wlzy2unadj$CI1[3], ", ", wlzy2unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wlzy2adj$ATE[3], ", (", wlzy2adj$CI1[3], ", ", wlzy2adj$CI2[3], ")"),
                       "Unadjusted" = paste(wlzy2unadj$ATE[4], ", (", wlzy2unadj$CI1[4], ", ", wlzy2unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wlzy2adj$ATE[4], ", (", wlzy2adj$CI1[4], ", ", wlzy2adj$CI2[4], ")")), stringsAsFactors=FALSE)


#HCZ Year 2
Nhczy2 <- nrow(h6_hcz_t3_vs_ts_t2gam.res)
hczy2unadj <- filter(h6unadj.res, Y == "hcz_t3")
hczy2adj <- filter(h6adj.res, Y == "hcz_t3")
tbl <- rbind(tbl, list("Outcome" = "HCZ, Year 2", "N" = Nhczy2, "Q1 Mean" = hczy2unadj$meanY[1], "Q2 Mean" =hczy2unadj$meanY[2], "Q3 Mean" = hczy2unadj$meanY[3], "Q4 Mean" = hczy2unadj$meanY[4],
                       "Unadjusted" = paste(hczy2unadj$ATE[2], ", (", hczy2unadj$CI1[2], ", ", hczy2unadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(hczy2adj$ATE[2], ", (", hczy2adj$CI1[2], ", ", hczy2adj$CI2[2], ")"),
                       "Unadjusted" = paste(hczy2unadj$ATE[3], ", (", hczy2unadj$CI1[3], ", ", hczy2unadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(hczy2adj$ATE[3], ", (", hczy2adj$CI1[3], ", ", hczy2adj$CI2[3], ")"),
                       "Unadjusted" = paste(hczy2unadj$ATE[4], ", (", hczy2unadj$CI1[4], ", ", hczy2unadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(lazy2adj$ATE[4], ", (", lazy2adj$CI1[4], ", ", lazy2adj$CI2[4], ")")), stringsAsFactors=FALSE)


#blank row
tbl <- rbind(tbl, list("Outcome"=" ", "N"=" ", "Q1 Mean"=" ", "Q2 Mean"=" ", "Q3 Mean"=" ", "Q4 Mean"=" ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" =" "), stringsAsFactors=FALSE)
```

```{r}
#Hypothesis 8
h8adj.res <- round_df(h8adj.res, 2)
h8unadj.res <- round_df(h8unadj.res, 2)

#Change in LAZ between Year 1 to Year 2
Nlaz <- nrow(h8_delta_laz_v_ts_t2gam.res)
lazunadj <- filter(h8unadj.res, Y == "delta_laz_t2_t3")
lazadj <- filter(h8adj.res, Y == "delta_laz_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Change in LAZ between Year 1 to Year 2", "N" = Nlaz, "Q1 Mean" = lazunadj$meanY[1], "Q2 Mean" =lazunadj$meanY[2], "Q3 Mean" = lazunadj$meanY[3], "Q4 Mean" = lazunadj$meanY[4],
                       "Unadjusted" = paste(lazunadj$ATE[2], ", (", lazunadj$CI1[2], ", ", lazunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(lazadj$ATE[2], ", (", lazadj$CI1[2], ", ", lazadj$CI2[2], ")"),
                       "Unadjusted" = paste(lazunadj$ATE[3], ", (", lazunadj$CI1[3], ", ", lazunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(lazadj$ATE[3], ", (", lazadj$CI1[3], ", ", lazadj$CI2[3], ")"),
                       "Unadjusted" = paste(lazunadj$ATE[4], ", (", lazunadj$CI1[4], ", ", lazunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(lazadj$ATE[4], ", (", lazadj$CI1[4], ", ", lazadj$CI2[4], ")")), stringsAsFactors=FALSE)

#Change in WAZ between Year 1 to Year 2
Nwaz <- nrow(h8_delta_waz_v_ts_t2gam.res)
wazunadj <- filter(h8unadj.res, Y == "delta_waz_t2_t3")
wazadj <- filter(h8adj.res, Y == "delta_waz_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Change in WAZ between Year 1 to Year 2", "N" = Nwaz, "Q1 Mean" = wazunadj$meanY[1], "Q2 Mean" =wazunadj$meanY[2], "Q3 Mean" = wazunadj$meanY[3], "Q4 Mean" = wazunadj$meanY[4],
                       "Unadjusted" = paste(wazunadj$ATE[2], ", (", wazunadj$CI1[2], ", ", wazunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wazadj$ATE[2], ", (", wazadj$CI1[2], ", ", wazadj$CI2[2], ")"),
                       "Unadjusted" = paste(wazunadj$ATE[3], ", (", wazunadj$CI1[3], ", ", wazunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wazadj$ATE[3], ", (", wazadj$CI1[3], ", ", wazadj$CI2[3], ")"),
                       "Unadjusted" = paste(wazunadj$ATE[4], ", (", wazunadj$CI1[4], ", ", wazunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wazadj$ATE[4], ", (", wazadj$CI1[4], ", ", wazadj$CI2[4], ")")), stringsAsFactors=FALSE)

#Change in WLZ between Year 1 to Year 2
Nwlz <- nrow(h8_delta_whz_v_ts_t2gam.res)
wlzunadj <- filter(h8unadj.res, Y == "delta_whz_t2_t3")
wlzadj <- filter(h8adj.res, Y == "delta_whz_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Change in WLZ between Year 1 to Year 2", "N" = Nwlz, "Q1 Mean" = wlzunadj$meanY[1], "Q2 Mean" =wlzunadj$meanY[2], "Q3 Mean" = wlzunadj$meanY[3], "Q4 Mean" = wlzunadj$meanY[4],
                       "Unadjusted" = paste(wlzunadj$ATE[2], ", (", wlzunadj$CI1[2], ", ", wlzunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(wlzadj$ATE[2], ", (", wlzadj$CI1[2], ", ", wlzadj$CI2[2], ")"),
                       "Unadjusted" = paste(wlzunadj$ATE[3], ", (", wlzunadj$CI1[3], ", ", wlzunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(wlzadj$ATE[3], ", (", wlzadj$CI1[3], ", ", wlzadj$CI2[3], ")"),
                       "Unadjusted" = paste(wlzunadj$ATE[4], ", (", wlzunadj$CI1[4], ", ", wlzunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(wlzadj$ATE[4], ", (", wlzadj$CI1[4], ", ", wlzadj$CI2[4], ")")), stringsAsFactors=FALSE)

#NEED TO FIX BC NOT FINDING VARIABLE?? SOMETHING WRONG WITH SOURCING
#Change in HCZ between Year 1 to Year 2
Nhcz <- nrow(h8_delta_hcz_v_ts_t2gam.res)
hczunadj <- filter(h8unadj.res, Y == "delta_hcz_t2_t3")
hczadj <- filter(h8adj.res, Y == "delta_hcz_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Change in HCZ between Year 1 to Year 2", "N" = Nhcz, "Q1 Mean" = hczunadj$meanY[1], "Q2 Mean" =hczunadj$meanY[2], "Q3 Mean" = hczunadj$meanY[3], "Q4 Mean" = hczunadj$meanY[4],
                       "Unadjusted" = paste(hczunadj$ATE[2], ", (", hczunadj$CI1[2], ", ", hczunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(hczadj$ATE[2], ", (", hczadj$CI1[2], ", ", hczadj$CI2[2], ")"),
                       "Unadjusted" = paste(hczunadj$ATE[3], ", (", hczunadj$CI1[3], ", ", hczunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(hczadj$ATE[3], ", (", hczadj$CI1[3], ", ", hczadj$CI2[3], ")"),
                       "Unadjusted" = paste(hczunadj$ATE[4], ", (", hczunadj$CI1[4], ", ", hczunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(hczadj$ATE[4], ", (", hczadj$CI1[4], ", ", hczadj$CI2[4], ")")), stringsAsFactors=FALSE)


#blank row
tbl <- rbind(tbl, list("Outcome"=" ", "N"=" ", "Q1 Mean"=" ", "Q2 Mean"=" ", "Q3 Mean"=" ", "Q4 Mean"=" ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" = " ",
                       "Unadjusted" = " ", 
                       "Fully adjusted" =" "), stringsAsFactors=FALSE)
```

```{r}
#Hypothesis 7
h7adj.res <- round_df(h7adj.res, 2)
h7unadj.res <- round_df(h7unadj.res, 2)

#Length velocity (cm/month)
Nlenv <- nrow(h7_len_veloc_vs_ts_t2gam.res)
lenvunadj <- filter(h7unadj.res, Y == "len_velocity_t2_t3")
lenvadj <- filter(h7adj.res, Y == "len_velocity_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Length velocity (cm/month)", "N" = Nlenv, "Q1 Mean" = lenvunadj$meanY[1], "Q2 Mean" =lenvunadj$meanY[2], "Q3 Mean" = lenvunadj$meanY[3], "Q4 Mean" = lenvunadj$meanY[4],
                       "Unadjusted" = paste(lenvunadj$ATE[2], ", (", lenvunadj$CI1[2], ", ", lenvunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(lenvadj$ATE[2], ", (", lenvadj$CI1[2], ", ", lenvadj$CI2[2], ")"),
                       "Unadjusted" = paste(lenvunadj$ATE[3], ", (", lenvunadj$CI1[3], ", ", lenvunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(lenvadj$ATE[3], ", (", lenvadj$CI1[3], ", ", lenvadj$CI2[3], ")"),
                       "Unadjusted" = paste(lenvunadj$ATE[4], ", (", lenvunadj$CI1[4], ", ", lenvunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(lenvadj$ATE[4], ", (", lenvadj$CI1[4], ", ", lenvadj$CI2[4], ")")), stringsAsFactors=FALSE)

#Weight velocity (kg/month)
Nweiv <- nrow(h7_wei_veloc_vs_ts_t2gam.res)
weivunadj <- filter(h7unadj.res, Y == "wei_velocity_t2_t3")
weivadj <- filter(h7adj.res, Y == "wei_velocity_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Length velocity (cm/month)", "N" = Nweiv, "Q1 Mean" = weivunadj$meanY[1], "Q2 Mean" =weivunadj$meanY[2], "Q3 Mean" = weivunadj$meanY[3], "Q4 Mean" = weivunadj$meanY[4],
                       "Unadjusted" = paste(weivunadj$ATE[2], ", (", weivunadj$CI1[2], ", ", weivunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(weivadj$ATE[2], ", (", weivadj$CI1[2], ", ", weivadj$CI2[2], ")"),
                       "Unadjusted" = paste(weivunadj$ATE[3], ", (", weivunadj$CI1[3], ", ", weivunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(weivadj$ATE[3], ", (", weivadj$CI1[3], ", ", weivadj$CI2[3], ")"),
                       "Unadjusted" = paste(weivunadj$ATE[4], ", (", weivunadj$CI1[4], ", ", weivunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(weivadj$ATE[4], ", (", weivadj$CI1[4], ", ", weivadj$CI2[4], ")")), stringsAsFactors=FALSE)

#Head circumference velocity (cm/month)
Nhcv <- nrow(h7_hc_veloc_vs_ts_t2gam.res)
hcvunadj <- filter(h7unadj.res, Y == "hc_velocity_t2_t3")
hcvadj <- filter(h7adj.res, Y == "hc_velocity_t2_t3")
tbl <- rbind(tbl, list("Outcome" = "Head circumference velocity (cm/month)", "N" = Nhcv, "Q1 Mean" = hcvunadj$meanY[1], "Q2 Mean" =hcvunadj$meanY[2], "Q3 Mean" = hcvunadj$meanY[3], "Q4 Mean" = hcvunadj$meanY[4],
                       "Unadjusted" = paste(hcvunadj$ATE[2], ", (", hcvunadj$CI1[2], ", ", hcvunadj$CI2[2], ")"), 
                       "Fully adjusted" = paste(hcvadj$ATE[2], ", (", hcvadj$CI1[2], ", ", hcvadj$CI2[2], ")"),
                       "Unadjusted" = paste(hcvunadj$ATE[3], ", (", hcvunadj$CI1[3], ", ", hcvunadj$CI2[3], ")"), 
                       "Fully adjusted" = paste(hcvadj$ATE[3], ", (", hcvadj$CI1[3], ", ", hcvadj$CI2[3], ")"),
                       "Unadjusted" = paste(hcvunadj$ATE[4], ", (", hcvunadj$CI1[4], ", ", hcvunadj$CI2[4], ")"), 
                       "Fully adjusted" = paste(hcvadj$ATE[4], ", (", hcvadj$CI1[4], ", ", hcvadj$CI2[4], ")")), stringsAsFactors=FALSE)
tbl
```

```{r}
tbl <- kable(tbl) %>%
  add_header_above((c(" "=6, "Coefficient (95% CI)"=2, "Coefficient (95% CI)"=2, "Coefficient (95% CI)"=2))) %>%
  add_header_above((c(" "=6, "T/S Ratio Year 1, Q1 v. Q2"=2, "T/S Ratio Year 1, Q1 v. Q3"=2,  "T/S Ratio Year 1, Q1 v. Q4"=2)))
tbl
```
```{r}
save_kable(tbl, file=here("tables/table2.html"))
```

